server:
  port: 8082
redisaux:
  limiter:
    dashboard:
      port: 1210
      ip: 127.0.0.1
#spring:
#  application:
#    name: mvcTest
#  redis:
#    database: 0   #  连接池最大阻塞等待时间（使用负值表示没有限制）
#    sentinel:
#      master: mymaster #主服务器所在集群名称
#      nodes:  localhost:26379,localhost:26479,localhost:26579