server:
  port: 8082
redisaux:
  limiter:
    dashboard:
      ip: 127.0.0.1
      port: 1210
      idleSec: 10
    groups:
      - id: 1
        remark: test
        tokenRateConfig:
          capacity: 2.0
          initToken: 3.0
          requestNeed: 1.0
          tokenRate: 3
        windowRateConfig:
          passCount: 5
          during: 1000
          unitMode: -1
        currentMode: 2
        blackRuleFallback: ip
        enableQPS: true
        unableURLPrefix: /user;/qq
        enableURLPrefix: /test
        urlFallBack: userBlack
      - id: 2
        remark: test2
        tokenRateConfig:
          capacity: 4.0
          initToken: 4.0
          requestNeed: 3.0
          tokenRate: 3
        windowRateConfig:
            passCount: 5
            during: 1000
            unitMode: -1
        currentMode: 2
        blackRuleFallback: ip
        enableQPS: true
        unableURLPrefix: /user;/qq
        enableURLPrefix: /test
        urlFallBack: userBlack
#spring:
#  application:
#    name: mvcTest
#  redis:
#    database: 0   #  连接池最大阻塞等待时间（使用负值表示没有限制）
#    sentinel:
#      master: mymaster #主服务器所在集群名称
#      nodes:  localhost:26379,localhost:26479,localhost:26579