server:
  port: 8082
redisaux:
  console:
    host: 10.0.75.1
  heartbeat:
    connect:
      timeout: 10000
    interval:
      ms: 10000
    lost:
      count: 3
      ms: 10000
#spring:
#  application:
#    name: mvcTest
#  redis:
#    database: 0   #  连接池最大阻塞等待时间（使用负值表示没有限制）
#    sentinel:
#      master: mymaster #主服务器所在集群名称
#      nodes:  localhost:26379,localhost:26479,localhost:26579